# Generated by Django 3.0.7 on 2020-07-23 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_entries', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='childThread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cThread', to='api.Thread'),
        ),
        migrations.AddField(
            model_name='entry',
            name='parentThread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pThread', to='api.Thread'),
        ),
    ]
