# Generated by Django 3.0.7 on 2020-07-24 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200723_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='group1',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='group2',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='string',
        ),
        migrations.AddField(
            model_name='thread',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Team'),
        ),
        migrations.AddField(
            model_name='topic',
            name='entriesComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='entryA',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entryA', to='api.Entry'),
        ),
        migrations.AddField(
            model_name='topic',
            name='entryB',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entryB', to='api.Entry'),
        ),
        migrations.AddField(
            model_name='topic',
            name='teamA',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamA', to='api.Team'),
        ),
        migrations.AddField(
            model_name='topic',
            name='teamB',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamB', to='api.Team'),
        ),
        migrations.AddField(
            model_name='topic',
            name='voter1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='voter1', to='api.Team'),
        ),
        migrations.AddField(
            model_name='topic',
            name='voter2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='voter2', to='api.Team'),
        ),
        migrations.AddField(
            model_name='topic',
            name='votingComplete',
            field=models.BooleanField(default=False),
        ),
    ]
