# Generated by Django 3.0.7 on 2020-07-25 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200724_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='team',
        ),
    ]
