# Generated by Django 3.0.7 on 2020-07-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_thread_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='teamA',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='teamB',
        ),
    ]
