# Generated by Django 3.0.7 on 2020-08-19 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200731_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='votingComplete',
        ),
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='teamA',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamA', to='api.Team'),
        ),
        migrations.AddField(
            model_name='topic',
            name='teamB',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamB', to='api.Team'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='childThread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cThread', to='api.Thread'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='parentThread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pThread', to='api.Thread'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='string',
            field=models.CharField(max_length=12000),
        ),
    ]
