# Generated by Django 3.0.7 on 2020-08-25 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200819_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='entryA',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entryA', to='api.Entry'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='entryB',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entryB', to='api.Entry'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='teamA',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamA', to='api.Team'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='teamB',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teamB', to='api.Team'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='voter1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='voter1', to='api.Team'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='voter2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='voter2', to='api.Team'),
        ),
    ]
